# Generated by Django 4.2.23 on 2025-07-08 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_number', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Order Number')),
                ('equipment_number', models.CharField(max_length=100, verbose_name='Equipment Number')),
                ('agreement_number', models.CharField(max_length=100, verbose_name='Agreement Number')),
                ('site_name', models.CharField(max_length=100, verbose_name='Site Name')),
                ('block', models.CharField(max_length=100, verbose_name='Block')),
                ('lift_number', models.CharField(max_length=100, verbose_name='Lift Number')),
                ('lift_quantity', models.IntegerField(verbose_name='Lift Quantity')),
                ('order_release', models.DateField(blank=True, verbose_name='Order Release Date')),
                ('supervisor_decided', models.DateField(blank=True, verbose_name='Supervisor Decided Date')),
                ('bom_ready', models.DateField(blank=True, verbose_name='BOM Ready Date')),
                ('gad_send_for_sign', models.DateField(blank=True, verbose_name='GAD Send for Sign Date')),
                ('kick_off_meeting', models.DateField(blank=True, verbose_name='Kick Off Meeting Date')),
                ('scaffolding_message', models.DateField(blank=True, verbose_name='Scaffolding Message Date')),
                ('scaffolding_delivery', models.DateField(blank=True, verbose_name='Scaffolding Delivery Date')),
                ('erector_file_ready', models.DateField(blank=True, verbose_name='Erector File Ready Date')),
                ('scaffolding_installation', models.DateField(blank=True, verbose_name='Scaffolding Installation Date')),
                ('reading_receipt', models.DateField(blank=True, verbose_name='Reading Receipt Date')),
                ('po_release', models.JSONField(blank=True, default=dict, verbose_name='PO Release')),
                ('material_dump', models.JSONField(blank=True, default=dict, verbose_name='Material Dump')),
                ('installation', models.DateField(blank=True, verbose_name='Installation Date')),
                ('lift_handover', models.DateField(blank=True, verbose_name='Lift Handover Date')),
                ('gad_sign_complete', models.DateField(blank=True, verbose_name='GAD Sign Complete Date')),
                ('form_a_submitted', models.DateField(blank=True, verbose_name='Form A Submitted Date')),
                ('form_a_permission_received', models.DateField(blank=True, verbose_name='Form Permission Received Date')),
                ('form_b_submitted', models.DateField(blank=True, verbose_name='Form B Submitted Date')),
                ('license_received', models.DateField(blank=True, verbose_name='License Received Date')),
                ('license_handover', models.DateField(blank=True, verbose_name='License Handover Date')),
                ('handover_oc_submitted', models.DateField(blank=True, verbose_name='Handover OC Submitted Date')),
                ('email_to_maintenance', models.DateField(blank=True, verbose_name='Email to Maintenance Date')),
                ('receipt_by_maintenance', models.DateField(blank=True, verbose_name='Receipt by Maintenance Date')),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed')], default='In Progress', max_length=100, verbose_name='Status')),
                ('sales_executive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sales Executive')),
                ('supervisor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='Historicalorder',
            fields=[
                ('order_number', models.CharField(db_index=True, max_length=100, verbose_name='Order Number')),
                ('equipment_number', models.CharField(max_length=100, verbose_name='Equipment Number')),
                ('agreement_number', models.CharField(max_length=100, verbose_name='Agreement Number')),
                ('site_name', models.CharField(max_length=100, verbose_name='Site Name')),
                ('block', models.CharField(max_length=100, verbose_name='Block')),
                ('lift_number', models.CharField(max_length=100, verbose_name='Lift Number')),
                ('lift_quantity', models.IntegerField(verbose_name='Lift Quantity')),
                ('order_release', models.DateField(blank=True, verbose_name='Order Release Date')),
                ('supervisor_decided', models.DateField(blank=True, verbose_name='Supervisor Decided Date')),
                ('bom_ready', models.DateField(blank=True, verbose_name='BOM Ready Date')),
                ('gad_send_for_sign', models.DateField(blank=True, verbose_name='GAD Send for Sign Date')),
                ('kick_off_meeting', models.DateField(blank=True, verbose_name='Kick Off Meeting Date')),
                ('scaffolding_message', models.DateField(blank=True, verbose_name='Scaffolding Message Date')),
                ('scaffolding_delivery', models.DateField(blank=True, verbose_name='Scaffolding Delivery Date')),
                ('erector_file_ready', models.DateField(blank=True, verbose_name='Erector File Ready Date')),
                ('scaffolding_installation', models.DateField(blank=True, verbose_name='Scaffolding Installation Date')),
                ('reading_receipt', models.DateField(blank=True, verbose_name='Reading Receipt Date')),
                ('po_release', models.JSONField(blank=True, default=dict, verbose_name='PO Release')),
                ('material_dump', models.JSONField(blank=True, default=dict, verbose_name='Material Dump')),
                ('installation', models.DateField(blank=True, verbose_name='Installation Date')),
                ('lift_handover', models.DateField(blank=True, verbose_name='Lift Handover Date')),
                ('gad_sign_complete', models.DateField(blank=True, verbose_name='GAD Sign Complete Date')),
                ('form_a_submitted', models.DateField(blank=True, verbose_name='Form A Submitted Date')),
                ('form_a_permission_received', models.DateField(blank=True, verbose_name='Form Permission Received Date')),
                ('form_b_submitted', models.DateField(blank=True, verbose_name='Form B Submitted Date')),
                ('license_received', models.DateField(blank=True, verbose_name='License Received Date')),
                ('license_handover', models.DateField(blank=True, verbose_name='License Handover Date')),
                ('handover_oc_submitted', models.DateField(blank=True, verbose_name='Handover OC Submitted Date')),
                ('email_to_maintenance', models.DateField(blank=True, verbose_name='Email to Maintenance Date')),
                ('receipt_by_maintenance', models.DateField(blank=True, verbose_name='Receipt by Maintenance Date')),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed')], default='In Progress', max_length=100, verbose_name='Status')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sales_executive', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Sales Executive')),
                ('supervisor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor')),
            ],
            options={
                'verbose_name': 'historical order',
                'verbose_name_plural': 'historical orders',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
