# Generated by Django 4.2.23 on 2025-07-08 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Xeom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='bom_ready',
            field=models.DateField(blank=True, null=True, verbose_name='BOM Ready Date'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='email_to_maintenance',
            field=models.DateField(blank=True, null=True, verbose_name='Email to Maintenance Date'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='erector_file_ready',
            field=models.DateField(blank=True, null=True, verbose_name='Erector File Ready Date'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='form_a_permission_received',
            field=models.DateField(blank=True, null=True, verbose_name='Form Permission Received Date'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='form_a_submitted',
            field=models.DateField(blank=True, null=True, verbose_name='Form A Submitted Date'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='form_b_submitted',
            field=models.DateField(blank=True, null=True, verbose_name='Form B Submitted Date'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='gad_send_for_sign',
            field=models.DateField(blank=True, null=True, verbose_name='GAD Send for Sign Date'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='gad_sign_complete',
            field=models.DateField(blank=True, null=True, verbose_name='GAD Sign Complete Date'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='handover_oc_submitted',
            field=models.DateField(blank=True, null=True, verbose_name='Handover OC Submitted Date'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='installation',
            field=models.DateField(blank=True, null=True, verbose_name='Installation Date'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='kick_off_meeting',
            field=models.DateField(blank=True, null=True, verbose_name='Kick Off Meeting Date'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='license_handover',
            field=models.DateField(blank=True, null=True, verbose_name='License Handover Date'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='license_received',
            field=models.DateField(blank=True, null=True, verbose_name='License Received Date'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='lift_handover',
            field=models.DateField(blank=True, null=True, verbose_name='Lift Handover Date'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='material_dump',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Material Dump'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='order_release',
            field=models.DateField(blank=True, null=True, verbose_name='Order Release Date'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='po_release',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='PO Release'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='reading_receipt',
            field=models.DateField(blank=True, null=True, verbose_name='Reading Receipt Date'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='receipt_by_maintenance',
            field=models.DateField(blank=True, null=True, verbose_name='Receipt by Maintenance Date'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='scaffolding_delivery',
            field=models.DateField(blank=True, null=True, verbose_name='Scaffolding Delivery Date'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='scaffolding_installation',
            field=models.DateField(blank=True, null=True, verbose_name='Scaffolding Installation Date'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='scaffolding_message',
            field=models.DateField(blank=True, null=True, verbose_name='Scaffolding Message Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='bom_ready',
            field=models.DateField(blank=True, null=True, verbose_name='BOM Ready Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email_to_maintenance',
            field=models.DateField(blank=True, null=True, verbose_name='Email to Maintenance Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='erector_file_ready',
            field=models.DateField(blank=True, null=True, verbose_name='Erector File Ready Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='form_a_permission_received',
            field=models.DateField(blank=True, null=True, verbose_name='Form Permission Received Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='form_a_submitted',
            field=models.DateField(blank=True, null=True, verbose_name='Form A Submitted Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='form_b_submitted',
            field=models.DateField(blank=True, null=True, verbose_name='Form B Submitted Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='gad_send_for_sign',
            field=models.DateField(blank=True, null=True, verbose_name='GAD Send for Sign Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='gad_sign_complete',
            field=models.DateField(blank=True, null=True, verbose_name='GAD Sign Complete Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='handover_oc_submitted',
            field=models.DateField(blank=True, null=True, verbose_name='Handover OC Submitted Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='installation',
            field=models.DateField(blank=True, null=True, verbose_name='Installation Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='kick_off_meeting',
            field=models.DateField(blank=True, null=True, verbose_name='Kick Off Meeting Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='license_handover',
            field=models.DateField(blank=True, null=True, verbose_name='License Handover Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='license_received',
            field=models.DateField(blank=True, null=True, verbose_name='License Received Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='lift_handover',
            field=models.DateField(blank=True, null=True, verbose_name='Lift Handover Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='material_dump',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Material Dump'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_release',
            field=models.DateField(blank=True, null=True, verbose_name='Order Release Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='po_release',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='PO Release'),
        ),
        migrations.AlterField(
            model_name='order',
            name='reading_receipt',
            field=models.DateField(blank=True, null=True, verbose_name='Reading Receipt Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='receipt_by_maintenance',
            field=models.DateField(blank=True, null=True, verbose_name='Receipt by Maintenance Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='scaffolding_delivery',
            field=models.DateField(blank=True, null=True, verbose_name='Scaffolding Delivery Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='scaffolding_installation',
            field=models.DateField(blank=True, null=True, verbose_name='Scaffolding Installation Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='scaffolding_message',
            field=models.DateField(blank=True, null=True, verbose_name='Scaffolding Message Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor'),
        ),
    ]
