# Generated by Django 4.2.23 on 2025-07-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Xeom', '0002_alter_historicalorder_bom_ready_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='supervisor_decided',
            field=models.DateField(blank=True, null=True, verbose_name='Supervisor Decided Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='supervisor_decided',
            field=models.DateField(blank=True, null=True, verbose_name='Supervisor Decided Date'),
        ),
    ]
