# Generated by Django 4.2.23 on 2025-07-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Xeom', '0003_alter_historicalorder_supervisor_decided_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='erector',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Erector Name'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='erector_decided',
            field=models.DateField(blank=True, null=True, verbose_name='Erector Decided Date'),
        ),
        migrations.AddField(
            model_name='order',
            name='erector',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Erector Name'),
        ),
        migrations.AddField(
            model_name='order',
            name='erector_decided',
            field=models.DateField(blank=True, null=True, verbose_name='Erector Decided Date'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='installation',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Installation Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='installation',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Installation Date'),
        ),
    ]
