# Generated by Django 4.2.23 on 2025-07-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Xeom', '0004_historicalorder_erector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='erector',
            field=models.CharField(blank=True, choices=[('SOVANJI', 'SOVANJI'), ('PRAVINBHAI', 'PRAVINBHAI'), ('ROSHANBHAI', 'ROSHANBHAI'), ('BHAVESHBHAI', 'BHAVESHBHAI'), ('JATINBHAI', 'JATINBHAI'), ('DIPAKBHAI', 'DIPAKBHAI'), ('KIRANBHAI', 'KIRANBHAI'), ('MUNAVARBHAI', 'MUNAVARBHAI'), ('KAUSHIKBHAI', 'KAUSHIKBHAI'), ('RAJU', 'RAJU'), ('ASHOKBHAI', 'ASHOKBHAI'), ('OM PRAKASH', 'OM PRAKASH')], max_length=100, null=True, verbose_name='Erector Name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='erector',
            field=models.CharField(blank=True, choices=[('SOVANJI', 'SOVANJI'), ('PRAVINBHAI', 'PRAVINBHAI'), ('ROSHANBHAI', 'ROSHANBHAI'), ('BHAVESHBHAI', 'BHAVESHBHAI'), ('JATINBHAI', 'JATINBHAI'), ('DIPAKBHAI', 'DIPAKBHAI'), ('KIRANBHAI', 'KIRANBHAI'), ('MUNAVARBHAI', 'MUNAVARBHAI'), ('KAUSHIKBHAI', 'KAUSHIKBHAI'), ('RAJU', 'RAJU'), ('ASHOKBHAI', 'ASHOKBHAI'), ('OM PRAKASH', 'OM PRAKASH')], max_length=100, null=True, verbose_name='Erector Name'),
        ),
    ]
